### ISSUE TITLE
K is not defined error when trying to install from manifest

### ISSUE THREAD

**Issue by 9littlebees** [brunocalado/old-crt-effects#1]
I can't install this, either from the list within Foundry (it doesn't show up) or from the manifest link, because the "K is not defined" error pops up. This is caused by your module being made for v10 but not having a valid manifest file for v9.

Considering this is intended to be used with the Alien RPG, which can currently only be played with Foundry v9, this module is currently unusable as is. I'd like to take a look at it, but can't until you've fixed it. Thanks!

**Comment by brunocalado** [comment]
It's hard for me to keep stuff for multiple fvtt versions. I have to stick with one.

You can install manually. Just download this v9 zip and and to your modules folder.
[old-crt-effects.zip](https://github.com/brunocalado/old-crt-effects/files/9640985/old-crt-effects.zip)
